name: lichess-data-pipeline-workflow 

on: 
  push:
  schedule: 
    - cron: "0 0 1 1-12 *" # run every 00:00 at day 1 from January to December
  workflow_dispatch: # manual trigger

jobs:
  run-data-pipeline:
    runs-on: windows-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4 
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run data pipeline
        env:  
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN}} # import lichess token
        run: python data-pipeline.py # run data pipeline
      - name: Check for changes # check env variable indicating if any changes were made
        id: git-check
        run: |
          echo "Git version:"
          git --version
          echo "Git config list:"
          git config --list 
          echo "Setting Git user name and email....."
          if (!(git config user.name 'github-actions')) || { Write-Error "Failed to set user.name"; exit 1 }
          if (!(git config user.email 'github-actions@github.com')) || { Write-Error "Failed to set user.email"; exit 1}
          echo "Adding changes....."
          git add .
          echo "Checking for changes....."
          if (git diff --staged --quiet) { echp "No changes detected"}   else { echo "changes=true" >> $env:GITHUB_ENV }
      - name: Commit and push if changes
        if: env.changes == 'true' # if changes made, push data to repo
        run: |
          git commit -m "updated record data"
          git push