name: lichess-data-pipeline-workflow 

on: 
  push:
  schedule: 
    - cron: "0 0 1 1-12 *" # run every 00:00 at day 1 from January to December
  workflow_dispatch: # manual trigger

jobs:
  run-data-pipeline:
    runs-on: windows-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4 
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN}}
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run data pipeline
        env:  
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN}} # import lichess token
        run: python data-pipeline.py # run data pipeline
      - name: Check for changes # check env variable indicating if any changes were made
        id: git-check
        run: |
          Write-Output "Git version:"
          git --version
          Write-Output "Git config list:"
          git config --list 
          Write-Output "Setting Git user name and email....."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          Write-Output "Adding changes....."
          git add .
          Write-Output "Checking for changes....."
          $changes = git diff --staged --exit-code
          if ($LASTEXITCODE -eq 1) {
            Write-Output "changes=true" >> $env:GITHUB_ENV
          } else {
            Write-Output "No changes detected"
          }
      - name: Commit and push if changes
        if: env.changes == 'true' # if changes made, push data to repo
        run: |
          git commit -m "updated record data"
          git push