name: lichess-data-pipeline-workflow

on: 
  push:
  schedule: 
    - cron: "0 0 1 1-12 *" # run every 00:00 at day 1 from January to December
  workflow_dispatch: # manual trigger

permissions:
  contents: write
  
jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4 
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Setup Python 
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt 
      - name: Run data pipeline
        env:  
          LICHESS_TOKEN: ${{ secrets.LICHESS_TOKEN }} # import lichess token
        run: python data-pipeline.py # run data pipeline
      - name: Check for changes
        id: git-check
        run: |
          echo "Git version:"
          git --version
          echo "Git config list:"
          git config --list 
          echo "Setting Git user name and email..."
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          echo "Checking for changes..."
          git add -A
          git add lichess-record-data/ # Ensure lichess-record-data folder is checked
          status=$(git status -s)
          if [ -n "$status" ]; then
            echo "changes=true" >> $GITHUB_ENV
            echo "Changes detected"
            echo "$status"
          else
            echo "No changes detected"
          fi
      - name: Commit and push if changes
        if: env.changes == 'true' # if changes made, push data to repo
        run: |
          echo "Committing changes..."
          git commit -m "updated record data"
          echo "Pushing changes..."
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git push